#!/usr/bin/env python

import sys, os

if len(sys.argv) != 2:
	print('no download dir')
	exit()

url = 'http://patatap.com/assets/'
ext = '.mp3'
letters = [ 'A', 'B', 'C', 'D', 'E', 'F' ] 
sounds = [
	'wipe',
	'veil',
	'prism-1',
	'prism-2',
	'prism-3',
	'clay',
	'piston-1',
	'piston-2',
	'piston-3',
	'flash-1',
	'flash-2',
	'flash-3',
	'dotted-spiral',
	'suspension',
	'confetti',
	'timer',
	'ufo',
	'splits',
	'moon',
	'strike',
	'zig-zag',
	'squiggle',
	'bubbles',
	'corona',
	'pinwheel',
	'glimmer',	
]

for l in letters:
	lpath = os.path.join(sys.argv[1], l)
	os.mkdir(lpath)
	for s in sounds:
		sfile = os.path.join(lpath, s + ext)
		surl = url + l + '/' + s + ext
		os.system('wget -O %s %s' % (sfile, surl))
